// Hard-coded hex values, kept in sync with CSS custom properties in base.css.
// Use these inside SVG attributes (setAttribute("stroke", ...)), because
// SVG presentation attributes do not resolve CSS var() references.
export const COLORS = {
  mint: "#c8e6d5",
  mintDeep: "#7ec8a6",
  peach: "#ffd6b8",
  peachDeep: "#f0a274",
  lavender: "#d9d2f5",
  lavenderDeep: "#9b8cd9",
  sky: "#bde0fe",
  skyDeep: "#6ba8e0",
  butter: "#fff3b8",
  butterDeep: "#e6c95a",
  rose: "#ffc4d1",
  roseDeep: "#e08097",
  text: "#2a2730",
  text2: "#5b5664",
  text3: "#8b8694",
  bg: "#fbf8f3",
  surface: "#ffffff",
  surface2: "#f5f1ea",
  surface3: "#ece6db",
  border: "#e5dfd3",
  borderStrong: "#d0c8b6",
  success: "#6dbf8b",
  successBg: "#d8f0e1",
  error: "#e88a8a",
  errorBg: "#fbdcdc",
  warning: "#e6b052",
  warningBg: "#fbe9c8",
  logic0: "#6ba8e0",
  logic0Bg: "#d4e8fa",
  logic1: "#f0a274",
  logic1Bg: "#ffe2cc",
  logicX: "#b5a8c9",
  logicXBg: "#ebe4f4",
};
